//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo
    {
        public int BookingInfoId { get; set; }
        public Nullable<int> Id { get; set; }
        public string pnr { get; set; }
    
        public virtual OrderResult OrderResult { get; set; }
    }
}
