//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkstraServis
    {
        public int Id { get; set; }
        public Nullable<bool> Tip { get; set; }
        public Nullable<decimal> ServisBedeli { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<bool> DonusEklensinMi { get; set; }
        public Nullable<int> KoltukLimiti { get; set; }
        public Nullable<decimal> LimiteBagliServisBedeli { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string KalkisKod { get; set; }
        public string KalkisSehir { get; set; }
        public string KalkisHavalimani { get; set; }
        public string VarisKod { get; set; }
        public string VarisSehir { get; set; }
        public string VarisHavalimani { get; set; }
        public string KalkisUlke { get; set; }
        public string VarisUlke { get; set; }
    }
}
