//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeyifliBiletEntities : DbContext
    {
        public KeyifliBiletEntities()
            : base("name=KeyifliBiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingInfo> BookingInfo { get; set; }
        public virtual DbSet<EBulten> EBulten { get; set; }
        public virtual DbSet<EkstraServis> EkstraServis { get; set; }
        public virtual DbSet<IletisimFormu> IletisimFormu { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Kutu> Kutu { get; set; }
        public virtual DbSet<KutuKategori> KutuKategori { get; set; }
        public virtual DbSet<legs> legs { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<MailKategori> MailKategori { get; set; }
        public virtual DbSet<Mailler> Mailler { get; set; }
        public virtual DbSet<Menuler> Menuler { get; set; }
        public virtual DbSet<MenuTipleri> MenuTipleri { get; set; }
        public virtual DbSet<OrderResult> OrderResult { get; set; }
        public virtual DbSet<passengers> passengers { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SayfaIcerigi> SayfaIcerigi { get; set; }
        public virtual DbSet<Sayfalar> Sayfalar { get; set; }
        public virtual DbSet<SayfaMultiMedia> SayfaMultiMedia { get; set; }
        public virtual DbSet<Siniflar> Siniflar { get; set; }
        public virtual DbSet<Sms> Sms { get; set; }
        public virtual DbSet<SmsKategori> SmsKategori { get; set; }
        public virtual DbSet<SosyalMedya> SosyalMedya { get; set; }
        public virtual DbSet<TakipKodlari> TakipKodlari { get; set; }
        public virtual DbSet<Tanimlar> Tanimlar { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
