//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutu
    {
        public int KategoriId { get; set; }
        public int KutuId { get; set; }
        public string Resim { get; set; }
        public Nullable<bool> IsOneWay { get; set; }
        public string DEP_Airport_Code { get; set; }
        public string DEP_Airport_Name { get; set; }
        public string DEP_Airport_CityName { get; set; }
        public Nullable<bool> DEP_Airport_IsCity { get; set; }
        public string ARR_Airport_Code { get; set; }
        public string ARR_Airport_Name { get; set; }
        public string ARR_Airport_CityName { get; set; }
        public Nullable<bool> ARR_Airport_IsCity { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual KutuKategori KutuKategori { get; set; }
    }
}
