//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class legs
    {
        public int LegsId { get; set; }
        public Nullable<int> Id { get; set; }
        public string operatorName { get; set; }
        public string aircraft { get; set; }
        public string arrivalAirport { get; set; }
        public string arrivalAirportName { get; set; }
        public string arrivalCityName { get; set; }
        public Nullable<System.DateTime> arrivalTime { get; set; }
        public string departureAirport { get; set; }
        public string departureAirportName { get; set; }
        public string departureCityName { get; set; }
        public Nullable<System.DateTime> departureTime { get; set; }
        public string flightNo { get; set; }
        public string localArrivalDate { get; set; }
        public string localDepartureDate { get; set; }
        public Nullable<bool> returnFlight { get; set; }
    
        public virtual OrderResult OrderResult { get; set; }
    }
}
