//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public string Metin { get; set; }
        public string Metod { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
