//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passengers
    {
        public int PassgengerId { get; set; }
        public Nullable<int> Id { get; set; }
        public string eticket { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string gender { get; set; }
        public string persontype { get; set; }
        public string serviceFee { get; set; }
        public string totalPrice { get; set; }
        public Nullable<double> agencyComission { get; set; }
        public string tax { get; set; }
        public string currency { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    
        public virtual OrderResult OrderResult { get; set; }
    }
}
