//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SayfaMultiMedia
    {
        public Nullable<int> SayfaId { get; set; }
        public int MultiMediaId { get; set; }
        public string Resim { get; set; }
    
        public virtual Sayfalar Sayfalar { get; set; }
    }
}
