//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sayfalar()
        {
            this.SayfaIcerigi = new HashSet<SayfaIcerigi>();
            this.SayfaMultiMedia = new HashSet<SayfaMultiMedia>();
        }
    
        public int SayfaId { get; set; }
        public Nullable<int> UstSayfaId { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public string SeoBasligi { get; set; }
        public string KeyWords { get; set; }
        public string SeoAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SayfaIcerigi> SayfaIcerigi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SayfaMultiMedia> SayfaMultiMedia { get; set; }
    }
}
