//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int SmsId { get; set; }
        public string ApiAdresi { get; set; }
        public string Mesaj { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string KaynakAdres { get; set; }
        public Nullable<bool> Durum { get; set; }
        public int SmsKategoriId { get; set; }
    
        public virtual SmsKategori SmsKategori { get; set; }
    }
}
