//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakipKodlari
    {
        public int TakipId { get; set; }
        public string Servis { get; set; }
        public Nullable<bool> Lokasyon { get; set; }
        public string Script { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
