//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyifliBilet.Areas.Yonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanimlar
    {
        public int TanimId { get; set; }
        public string SiteAdi { get; set; }
        public string Mail { get; set; }
        public string Url { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Adres { get; set; }
        public string Harita { get; set; }
    }
}
